apiVersion: v1
kind: Secret
metadata:
  name: stock-supplier-postgres
  namespace: production2
  labels:
    app: stock-supplier-postgres2
type: Opaque
data:
  postgres-password:  "c3RvY2tzdXBwbGllcg=="
