---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
  labels:
    app.kubernetes.io/instance: stock-supplier
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: stock-supplier
    app.kubernetes.io/version: 4.1.0-20200708125252.932
    helm.sh/chart: stock-supplier-4.1.0-20200708125252.932
    release: stock-supplier
  name: stock-supplier
  namespace: production
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: stock-supplier
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: turing-polling-publisher
    app.kubernetes.io/version: 7.8.7
    helm.sh/chart: turing-polling-publisher-7.8.7
  name: stock-supplier-turing-polling-publisher
$patch: delete
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: stock-supplier
  namespace: production
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: stock-supplier-postgres
  namespace: production

---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: stock-supplier-lost-items-publisher

---
