---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: stock-supplier
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: turing-polling-publisher
    app.kubernetes.io/version: 7.8.7
    helm.sh/chart: turing-polling-publisher-7.8.7
  name: stock-supplier-turing-polling-publisher
$patch: delete
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: stock-supplier
  namespace: production
---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: stock-supplier-postgres
  namespace: production

---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: stock-supplier-lost-items-publisher

---
