kind: ConfigMap
apiVersion: v1
metadata:
  name: stock-supplier-lost-items-publisher
  namespace: production
  annotations:
data:
  application.yaml: |-
    spring:
      profile: prod
      kafka:
        bootstrap-servers: kafka.production:9092
    opentracing:
      jaeger:
        enabled: false
    vanderlande:
       scheduler:
         event-publisher:
           enabled: true
           resignTime: 2
           cron: 0 0 3 * * *
