# Default values for stock-supplier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vicentral.azurecr.io/vanderlande/wpp/fm_ssu/stock-supplier
  tag: ${#triggerResolvedArtifactByType('docker/image')['version']}
  pullPolicy: IfNotPresent
  pullSecret: default-docker-registry
  
service:
  type: ClusterIP
  port: 443

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  path: /stock-supplier
  host: team2-vanderlande.westeurope.cloudapp.azure.com
  tls: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: ""
fullnameOverride: ""

database:
  # Username and password for postgresql have to be aligned with the one in the postgresql section
  username: stocksupplier
  password: stocksupplier

turing-polling-publisher:
  enabled: true

lost-items-publisher:
  enabled: true

postgresql:
  # even if postgresql is selected in the global database configuration, it must also be enabled here
  # enabled: true
  enabled: true
  #fullnameOverride: stock-supplier-postgres
  nameOverride: stock-supplier-postgres
  postgresUser: stocksupplier
  postgresPassword: stocksupplier
  postgresDatabase: stocksupplier
  persistence:
    persistence.size: 1Gi
    persistence.storageClass: rook-ceph-block

global:
  certificates:
    enabled: true
  database:
    # The database type to use
    type: postgresql
    # type: oracle
    # The jdbc url to use. In case of postgresql use
    url: "jdbc:postgresql://stock-supplier-postgres:5432/stocksupplier"
    # url: "jdbc:oracle:thin:@${TNS_ALIAS}?TNS_ADMIN=/etc/oracle"
    pwSecret:
      name: "{{ .Release.Name }}-db-auth"
      key: password
    userSecret:
      name: "{{ .Release.Name }}-db-auth"
      key: username

certificates:
  loadAdditionalRoots: false
