# Default values for stock-supplier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

Release:
  Name: stocksupplier-stock-supplier

image:
  repository: vicentral.azurecr.io/vanderlande/wpp/fm_ssu/stock-supplier
  tag: ${#triggerResolvedArtifactByType('docker/image')['version']}
  pullPolicy: IfNotPresent
  pullSecret: default-docker-registry

kafka:
  broker: kafka.production:9092
services:
  url:
    adaptoLoadingMock: http://wiremock.pocket-sorter.svc.cluster.local/adapto-loading-mock/api
    stockBroker: http://wiremock.pocket-sorter.svc.cluster.local/stock-broker/api
    consignmentPlanner: http://wiremock.pocket-sorter.svc.cluster.local/consignment-planner/api

processareas: |
  - processAreaId: '440ddf13-c01e-4119-937e-7371863e5441'
    processAreaName: 'Decanting'
    processAreaType: 'Decanting'
    consumptionAndProvision: 'coupled'
    processDomainService: 'stock-supplier'
  - processAreaId: '617918a6-b819-11e8-96f8-529269fb1459'
    processAreaName: 'Adapto Storage'
    processAreaType: 'Adapto'
    consumptionAndProvision: 'decoupled'
    processDomainService: 'stock-supplier'
  - processAreaId: '7b92d218-b819-11e8-96f8-529269fb1459'
    processAreaName: 'GTP1'
    processAreaType: 'GTP'
    consumptionAndProvision: 'coupled'
    processDomainService: 'stock-supplier'
  - processAreaId: '85feef84-6991-46ac-b31c-48bc992cef9e'
    processAreaName: 'Palletiser'
    processAreaType: 'Palletiser'
    consumptionAndProvision: 'coupled'
    processDomainService: 'stock-supplier'
  - processAreaId: '6fa34787-d85c-49ef-826e-6253a8c12646'
    processAreaName: 'Allocation'
    processAreaType: 'Allocation'
    consumptionAndProvision: 'decoupled'
    processDomainService: 'stock-allocator'
  - processAreaId: '4e9aa42f-78fb-4b4d-82b8-e98dd3e60b4b'
    processAreaName: 'Package Finalizer'
    processAreaType: 'Package Finalizer'
    consumptionAndProvision: 'decoupled'
    processDomainService: 'Package Finalizer'
  - processAreaId: 'ec527f8f-0af9-4117-8af3-2e27c7ec4ffc'
    processAreaName: 'Clearing'
    processAreaType: 'Clearing'
    consumptionAndProvision: 'coupled'
    processDomainService: 'stock-supplier'

dataRetention:
  cleanerDisabled: false
  cleanerInterval: "0 0 3 * * *"
  minutesToKeepData : 4320
  maxRemovePerRun: 1000

service:
  type: ClusterIP
  port: 443

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  path: /stock-supplier
  host: team2-vanderlande.westeurope.cloudapp.azure.com
  tls: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: ""
fullnameOverride: ""

database:
  # Username and password for postgresql have to be aligned with the one in the postgresql section
  # username: stocksupplier
  username: STOCKSUPPLIER
  # password: stocksupplier
  password: STOCKSUPPLIER

turing-polling-publisher:
  enabled: true

lost-items-publisher:
  enabled: true

postgresql:
  # even if postgresql is selected in the global database configuration, it must also be enabled here
  # enabled: true
  enabled: true
  #fullnameOverride: stock-supplier-postgres
  nameOverride: stock-supplier-postgres
  postgresUser: stocksupplier
  postgresPassword: stocksupplier
  postgresDatabase: stocksupplier
  persistence:
    persistence.size: 1Gi
    persistence.storageClass: rook-ceph-block

global:
  certificates:
    enabled: true
  database:
    # The database type to use
    type: postgresql
    # type: oracle
    # The jdbc url to use. In case of postgresql use
    url: "jdbc:postgresql://stock-supplier-postgres:5432/stocksupplier"
    # url: "jdbc:oracle:thin:@${TNS_ALIAS}?TNS_ADMIN=/etc/oracle"
    pwSecret:
      name: "{{ .Release.Name }}-db-auth"
      key: password
    userSecret:
      name: "{{ .Release.Name }}-db-auth"
      key: username

certificates:
  loadAdditionalRoots: false
